CONFIGPATH = '/etc/eko/'
SENSORPATH = '/etc/eko/sensors/'
DATAPATH = '/data/'
ZIPPATH = '/zipfiles/'
SENSOR_DEFCONFIG = '/etc/eko/sensor_default.cfg'
VERSION = '1.0.4'
URLUploadRequest = 'http://www.ekohub.org/api/upload_request'
URLJsonAPI = 'http://www.ekohub.org/api/json'